services:
  app:
    build: .
    ports:
      - "${PORT_NUMBER}:${PORT_NUMBER}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST_NAME=${HOST_NAME}
      - HOME_DETAILS=${HOME_DETAILS}
      - MODEL=${MODEL}
      - PORT_NUMBER=${PORT_NUMBER}