import os
from openai import OpenAI

# Global variable for the default OpenAI client, initialized using environment API key
_default_openai_client = None

def get_openai_client(api_key=None):
    global _default_openai_client
    if api_key:
        # If a specific API key is provided, create a new client instance for it
        return OpenAI(api_key=api_key)
    else:
        # If no specific key, use the default (environment-based) client
        if _default_openai_client is None:
            env_api_key = os.getenv("OPENAI_API_KEY")
            if not env_api_key:
                raise ValueError("OpenAI API key not provided (and not found in environment variables).")
            _default_openai_client = OpenAI(api_key=env_api_key)
        return _default_openai_client

def convert_rating_to_description(rating):
    # Convert the rating to a description, change the discriptions as needed
    return {
        '1': 'Terrible',
        '2': 'Good',
        '3': 'Great'
    }.get(rating, 'unknown')

def generate_review(name, rating, communication, cleanliness, house_rules, comments, host_name, model, api_key=None): # Removed home_details as it's not used
    # Convert the ratings to descriptions
    rating_description = convert_rating_to_description(rating)
    communication_description = convert_rating_to_description(communication)
    cleanliness_description = convert_rating_to_description(cleanliness)
    house_rules_description = convert_rating_to_description(house_rules)
    # Generate the prompt for the model to then use
    prompt = (
        f"Generate a brief, kind, polite, and professional guest review for Airbnb which I ({host_name}) host based on the following details:\n" # Added host_name
        f"Name: {name}\n"
        f"Rating: {rating_description}\n"
        f"Communication: {communication_description}\n"
        f"Cleanliness: {cleanliness_description}\n"
        f"House Rules: {house_rules_description}\n"
        f"Comments: {comments}\n"
        "The review should be less than 4 sentences long. One emoji can be used."
    )
    # Call the model to generate the review
    client = get_openai_client(api_key)
    response = client.chat.completions.create(
        model=model, # Use passed-in model
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

def generate_private_note_to_guest(name, rating, communication, cleanliness, house_rules, private_note, host_name, home_details, model, api_key=None):
    # Convert the ratings to descriptions
    rating_description = convert_rating_to_description(rating)
    communication_description = convert_rating_to_description(communication)
    cleanliness_description = convert_rating_to_description(cleanliness)
    house_rules_description = convert_rating_to_description(house_rules)
    # Generate the prompt for the model to then use
    prompt = (
        f"Generate a private note to the guest for Airbnb which I host based on the following details:\n"
        f"Guest Name: {name}\n"
        f"Guest Overall Rating: {rating_description}\n"
        f"Communication: {communication_description}\n"
        f"Cleanliness: {cleanliness_description}\n"
        f"House Rules: {house_rules_description}\n"
        f"Private Note: {private_note}\n"
        f"Home Details: {home_details}\n" # Use passed-in home_details
        f"My name is {host_name} and I am the host of this Airbnb listing.\n" # Use passed-in host_name
        "The note should be less than 4 sentences long, friendly, and should welcome the guest back anytime. One emoji can be used. The goal of the note should be influencing the guest to save our Airbnb listing for next time."
    )
    # Call the model to generate the private note
    client = get_openai_client(api_key)
    response = client.chat.completions.create(
        model=model, # Use passed-in model
        messages=[{"role": "user", "content": prompt}]
    )
    # Return the private note generated by the model
    return response.choices[0].message.content.strip()

def generate_review_request(name, review, private_note, host_name, model, api_key=None):
    # Generate the prompt for the model to then use
    if private_note:
        prompt = (
            f"Generate a message to the guest letting them know you just reviewed them and that you would like them to review you back when they have a chance. Include a snippet of the review you left for them.\n"
            f"Guest Name: {name}\n"
            f"Review to include a snippet of: {review}\n"
            f"Private Note to consider : {private_note}\n"
            f"My name is {host_name} I am the host.\n" # Use passed-in host_name
            "The message should be less than 4 sentences long, friendly, and should encourage the guest to leave a review. 1-3 emoji can be used."
        )
    else:
        prompt = (
            f"Generate a message to the guest letting them know you just reviewed them and that you would like them to review you back when they have a chance. Include a snippet of the review you left for them.\n"
            f"Guest Name: {name}\n"
            f"Review to include a snippet of: {review}\n"
            f"My name is {host_name} I am the host.\n" # Use passed-in host_name
            "The message should be less than 4 sentences long, friendly, and should encourage the guest to leave a review. 1-3 emoji can be used."
        )
    # Call the model to generate the message
    client = get_openai_client(api_key)
    response = client.chat.completions.create(
        model=model, # Use passed-in model
        messages=[{"role": "user", "content": prompt}]
    )
    # Return the message generated by the model
    return response.choices[0].message.content.strip()
